version: 2

sources:
  - name: snowflake_sample_data
    description: "Sample table provided by SF"
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCDS_SF10TCL
    tables:
      - name: store_sales
        description: "Sales info"
